### ISSUE TITLE
Errors on Hassio.. about appdaemon...

### ISSUE THREAD

**Issue by vpomax** [hassio-addons/addon-appdaemon2#10]
I have Home Assistant 0.64 and Hassio 0.95 on my Raspberry Pi 3

From three days after restarting Hassio it show me the following error...

18-02-25 22:20:26 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:27 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:27 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:27 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:27 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons
18-02-25 22:20:28 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:28 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons
18-02-25 22:20:29 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:29 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:29 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:29 WARNING (MainThread) [hassio.api.security] Invalid token for access /addons/a0d7b954_appdaemon/info
18-02-25 22:20:30 WARNING (MainThread) [hassio.api.security] Invalid token for access /supervisor/info

What's happening?

**Comment by frenck** [comment]
It is a warning, which, for now, can be safely ignored.
A new security layer is being added, which is not yet used by this add-on.
This security is not enforced yet, but it throws a warning in case it detects it is not being used.

Will be solved in an upcoming version.

**Comment by vpomax** [comment]
it creates several problems, samba does not work, appdaemon does not work properly, my lights under mqtt do not work properly

**Comment by frenck** [comment]
You must have another issue. The new security layer is NOT enforced, hence it is a WARNING and not an error. This is not the error causing those issues for sure.

Secondly, this add-on has nothing to do with samba or any of the other stuff you've just listed.

**Comment by frenck** [comment]
(Sorry did not mean to close the issue, wrong button 😨 )

**Comment by frenck** [comment]
A fix for the warning has been build and is currently in the master branch.
The warning will be gone in the next release.

**Comment by vpomax** [comment]
Ok, thank you, I will wait for next release
