### ISSUE TITLE
Error handling request since updating to 1.1.0

### ISSUE THREAD

**Issue by suhajdab** [hassio-addons/addon-appdaemon2#11]
# Problem/Motivation

Just updated this add-on to 1.1.0 running on hass.io 0.64.2, and suddenly dashboards don't work. They do load and display, but tapping buttons, now only log an error.

Config:
```
{
  "log_level": "info",
  "commtype": "sse",
  "system_packages": [],
  "python_packages": []
}
```

## Expected behavior

Dashboard buttons should turn lights on/off.

## Actual behavior

AppDaemon2 log displays:
```
2018-03-02 20:22:09.403862 INFO New dashboard connected: Kitchen Panel
2018-03-02 20:22:23.435239 WARNING Excessive time spent in scheduler loop: 5428.0ms
2018-03-02 20:22:23.437046 WARNING Scheduler clock skew detected - delta = 4.433150053024292 - resetting
Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_app.py", line 310, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 213, in coro
    res = yield from res
  File "/usr/lib/python3.6/site-packages/appdaemon/rundash.py", line 181, in call_service
    data = yield from request.post()
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
```
In the browser console:
```
POST http://10.0.1.160:5050/call_service 500 (Internal Server Error)
send @ jquery-3.1.1.min.js:4
ajax @ jquery-3.1.1.min.js:4
r.(anonymous function) @ jquery-3.1.1.min.js:4
WidgetBase.call_service @ dashboard.js:217
OnButtonClick @ application.js:1244
(anonymous) @ dashboard.js:238
dispatch @ jquery-3.1.1.min.js:3
q.handle @ jquery-3.1.1.min.js:3
```

**Comment by frenck** [comment]
Hmmm @acockburn, any ideas?

**Comment by acockburn** [comment]
The OP doesn't state the version of AD he is using but it looks like 2.x. He is using python 3.6 and I have fixed several 3.6 issues in AD 3.0b4 so I recommend an upgrade.

**Comment by frenck** [comment]
@acockburn He is running 2.x indeed, which is still considered stable right?

**Comment by acockburn** [comment]
Correct - but I was not planning to maintain it any further as 3.0 is just around the corner and there is a viable upgrade strategy. If there is demand I can release a 2.x fix for this but I wasn't planning to, as I'd rather users migrate to 3.0.

**Comment by poblabs** [comment]
FYI - I had this error today as well. I almost created an issue here but I read this one instead :) 

I didn't know 3.0 was released. I migrated over to 3.0 (had some confusion with the change of appdaemon.yaml layout but looking at the GitHub repo helped), and so far so good. Maybe something should be put into the 2.0 package to suggest updating to 3.0 if there's errors?

**Comment by acockburn** [comment]
3.0 is still officially in Beta, but I will release it officially this
weekend. At that point I'll add that to the docs and include upgrade steps
etc.

**Comment by suhajdab** [comment]
Yes, it was the latest 2.x, but I too have switched to 3.0 since.

**Comment by frenck** [comment]
This add-on is now officially deprecated. AppDaemon3 has been declared stable.
