### ISSUE TITLE
OPEN WEB UI with SSL

### ISSUE THREAD

**Issue by TheRedBull205** [hassio-addons/addon-appdaemon2#6]
# Problem

> "OPEN WEB UI" in hass.io client side doesn't use SSL if "on" to redirect's to https://
![knipsel](https://user-images.githubusercontent.com/17354992/34575350-b2bcac3e-f17a-11e7-8f0b-4378071e2442.PNG)

## Expected behavior

> If SSL is "on" set "http://" to "https://"
> See "/appdaemon/config.json" for  ""webui": "http://[HOST]:[PORT:5050]","
> 
> Dont know how to fix this on the dev side.

**Comment by frenck** [comment]
This is unfixable.

The SSL part is managed by AppDaemon itself, not by Hass.io. Therefore Hass.io is unable to determine the difference.

I've chosen the button to work with the "out-of-the-box" case.
