### ISSUE TITLE
Update/refresh of Dashboard

### ISSUE THREAD

**Issue by r-jordan** [hassio-addons/addon-appdaemon2#8]
Hi,

I've seen this topic in the forum about the problem about refreshing the Dashboard:

[https://community.home-assistant.io/t/how-do-i-update-widget-state-without-dashboard-page-refresh-please-help-resolved/27004/5](https://community.home-assistant.io/t/how-do-i-update-widget-state-without-dashboard-page-refresh-please-help-resolved/27004/5)

It seems that it's refered to the Hassio addon of Appdaemon because in a python environment installation the problem does not exist.

Is someone working in this issue?

## Expected behavior

Information in the dashboard should be refreshed instantanously when any entity state is updated on homeassistant.

## Actual behavior

Dashboard has to be reloaded from the browser to refresh it.

**Comment by frenck** [comment]
I need a reproduction scenario or something.
This does not say anything.

**Comment by r-jordan** [comment]
I've just reproduced again with the following installation:

RaspberryPi3
Hassio 0.95 
HA 0.63.3
Addon AppDaemon3 0.1.0

I've added a switch entity that I had already configured in the Hello Dashboard:

layout:
    - label(2x2), switch.switch_5_1

Procedure to reproduce:

First: Switch on the switch. You can do it through the Dashboard to test it's working correctly.
Second: Switch off the switch through Home Assistant interface.

Then check that the switch is still on in the Dashboard. It only update the state when the Hello Dashboard page is reloaded in the browser (Chrome).

Thanks for your help!

**Comment by frenck** [comment]
You are reporting into the wrong repository.
This is the repository and issue tracker of AppDaemon2.

**Comment by r-jordan** [comment]
I've just retried with HA 0.64.1 and Addon Appdaemon2 1.1.0 with the same result.
You may consider to reopen it.

**Comment by frenck** [comment]
Check, I think @acockburn might be of some value on this issue?

**Comment by acockburn** [comment]
I think this is due to issues with python 3.6 that were fixed in AppDaemon b4.

**Comment by frenck** [comment]
This add-on is now officially deprecated. AppDaemon3 has been declared stable.
